# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: i18n.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ni18n.proto\"=\n\tTranslate\x12\x10\n\x03src\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\n\n\x02to\x18\x02 \x01(\t\x12\n\n\x02li\x18\x03 \x03(\tB\x06\n\x04_src\"\x18\n\nTranslateA\x12\n\n\x02li\x18\x01 \x03(\t2.\n\x04I18n\x12&\n\ttranslate\x12\n.Translate\x1a\x0b.TranslateA\"\x00\x62\x06proto3')



_TRANSLATE = DESCRIPTOR.message_types_by_name['Translate']
_TRANSLATEA = DESCRIPTOR.message_types_by_name['TranslateA']
Translate = _reflection.GeneratedProtocolMessageType('Translate', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATE,
  '__module__' : 'i18n_pb2'
  # @@protoc_insertion_point(class_scope:Translate)
  })
_sym_db.RegisterMessage(Translate)

TranslateA = _reflection.GeneratedProtocolMessageType('TranslateA', (_message.Message,), {
  'DESCRIPTOR' : _TRANSLATEA,
  '__module__' : 'i18n_pb2'
  # @@protoc_insertion_point(class_scope:TranslateA)
  })
_sym_db.RegisterMessage(TranslateA)

_I18N = DESCRIPTOR.services_by_name['I18n']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSLATE._serialized_start=14
  _TRANSLATE._serialized_end=75
  _TRANSLATEA._serialized_start=77
  _TRANSLATEA._serialized_end=101
  _I18N._serialized_start=103
  _I18N._serialized_end=149
# @@protoc_insertion_point(module_scope)
